number_of_target: 4
x_pos: [0, 6, 6, 0]
y_pos: [0, 0, 6, 6]
z_pos: [5, 5, 5, 5]
target_error: 0.1

number_of_goal: 3
latitude: [21.0065275, 21.0065305, 21.0065295]
longitude: [105.8428991, 105.8432921, 105.8430000]
altitude: [7, 7, 7] 
goal_error: 0.3 

z_takeoff: 3

hover_time: 10
unpack_time: 15

desired_velocity: 0.3
land_velocity: 0.7
return_velcity: 1
